greeting: Hello, NICE to meet you!   

spring:
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${zipkin_collector_host:http://zipkin.169.56.84.41.nip.io}:${zipkin_collector_port:80}
    
